// Auto-generated by commands/_internal/generate.ts -- do not edit
import cmdAgentsMd from '../agents-md/generate.ts';
import cmdAskAnswer from '../ask/answer.ts';
import cmdAskCleanup from '../ask/cleanup.ts';
import cmdAskCreate from '../ask/create.ts';
import cmdAskList from '../ask/list.ts';
import cmdConfigAgent from '../config/agent.ts';
import cmdConfigGet from '../config/get.ts';
import cmdConfigSet from '../config/set.ts';
import cmdContextArchive from '../context/archive.ts';
import cmdContextCompile from '../context/compile.ts';
import cmdContextDelete from '../context/delete.ts';
import cmdContextList from '../context/list.ts';
import cmdContextRead from '../context/read.ts';
import cmdContextStats from '../context/stats.ts';
import cmdContextWrite from '../context/write.ts';
import cmdFeatureActive from '../feature/active.ts';
import cmdFeatureComplete from '../feature/complete.ts';
import cmdFeatureCreate from '../feature/create.ts';
import cmdFeatureInfo from '../feature/info.ts';
import cmdFeatureList from '../feature/list.ts';
import cmdInit from '../init/run.ts';
import cmdPlanApprove from '../plan/approve.ts';
import cmdPlanComment from '../plan/comment.ts';
import cmdPlanCommentsClear from '../plan/comments-clear.ts';
import cmdPlanRead from '../plan/read.ts';
import cmdPlanRevoke from '../plan/revoke.ts';
import cmdPlanWrite from '../plan/write.ts';
import cmdSandboxStatus from '../sandbox/status.ts';
import cmdSandboxWrap from '../sandbox/wrap.ts';
import cmdSelfUpdate from '../update/self.ts';
import cmdSessionEnd from '../session/end.ts';
import cmdSessionFork from '../session/fork.ts';
import cmdSessionFresh from '../session/fresh.ts';
import cmdSessionInfo from '../session/info.ts';
import cmdSessionList from '../session/list.ts';
import cmdSessionMaster from '../session/master.ts';
import cmdSessionTrack from '../session/track.ts';
import cmdSkill from '../skill/load.ts';
import cmdSkillList from '../skill/list.ts';
import cmdStatus from '../status/show.ts';
import cmdSubtaskCreate from '../subtask/create.ts';
import cmdSubtaskDelete from '../subtask/delete.ts';
import cmdSubtaskInfo from '../subtask/info.ts';
import cmdSubtaskList from '../subtask/list.ts';
import cmdSubtaskReportRead from '../subtask/report-read.ts';
import cmdSubtaskReportWrite from '../subtask/report-write.ts';
import cmdSubtaskSpecRead from '../subtask/spec-read.ts';
import cmdSubtaskSpecWrite from '../subtask/spec-write.ts';
import cmdSubtaskUpdate from '../subtask/update.ts';
import cmdTaskCreate from '../task/create.ts';
import cmdTaskFinish from '../task/finish.ts';
import cmdTaskInfo from '../task/info.ts';
import cmdTaskList from '../task/list.ts';
import cmdTaskReportRead from '../task/report-read.ts';
import cmdTaskReportWrite from '../task/report-write.ts';
import cmdTaskSpecRead from '../task/spec-read.ts';
import cmdTaskSpecWrite from '../task/spec-write.ts';
import cmdTaskStart from '../task/start.ts';
import cmdTaskSync from '../task/sync.ts';
import cmdTaskUpdate from '../task/update.ts';
import cmdUpdate from '../update/run.ts';

export const subCommands = {
  'agents-md': cmdAgentsMd,
  'ask-answer': cmdAskAnswer,
  'ask-cleanup': cmdAskCleanup,
  'ask-create': cmdAskCreate,
  'ask-list': cmdAskList,
  'config-agent': cmdConfigAgent,
  'config-get': cmdConfigGet,
  'config-set': cmdConfigSet,
  'context-archive': cmdContextArchive,
  'context-compile': cmdContextCompile,
  'context-delete': cmdContextDelete,
  'context-list': cmdContextList,
  'context-read': cmdContextRead,
  'context-stats': cmdContextStats,
  'context-write': cmdContextWrite,
  'feature-active': cmdFeatureActive,
  'feature-complete': cmdFeatureComplete,
  'feature-create': cmdFeatureCreate,
  'feature-info': cmdFeatureInfo,
  'feature-list': cmdFeatureList,
  'init': cmdInit,
  'plan-approve': cmdPlanApprove,
  'plan-comment': cmdPlanComment,
  'plan-comments-clear': cmdPlanCommentsClear,
  'plan-read': cmdPlanRead,
  'plan-revoke': cmdPlanRevoke,
  'plan-write': cmdPlanWrite,
  'sandbox-status': cmdSandboxStatus,
  'sandbox-wrap': cmdSandboxWrap,
  'self-update': cmdSelfUpdate,
  'session-end': cmdSessionEnd,
  'session-fork': cmdSessionFork,
  'session-fresh': cmdSessionFresh,
  'session-info': cmdSessionInfo,
  'session-list': cmdSessionList,
  'session-master': cmdSessionMaster,
  'session-track': cmdSessionTrack,
  'skill': cmdSkill,
  'skill-list': cmdSkillList,
  'status': cmdStatus,
  'subtask-create': cmdSubtaskCreate,
  'subtask-delete': cmdSubtaskDelete,
  'subtask-info': cmdSubtaskInfo,
  'subtask-list': cmdSubtaskList,
  'subtask-report-read': cmdSubtaskReportRead,
  'subtask-report-write': cmdSubtaskReportWrite,
  'subtask-spec-read': cmdSubtaskSpecRead,
  'subtask-spec-write': cmdSubtaskSpecWrite,
  'subtask-update': cmdSubtaskUpdate,
  'task-create': cmdTaskCreate,
  'task-finish': cmdTaskFinish,
  'task-info': cmdTaskInfo,
  'task-list': cmdTaskList,
  'task-report-read': cmdTaskReportRead,
  'task-report-write': cmdTaskReportWrite,
  'task-spec-read': cmdTaskSpecRead,
  'task-spec-write': cmdTaskSpecWrite,
  'task-start': cmdTaskStart,
  'task-sync': cmdTaskSync,
  'task-update': cmdTaskUpdate,
  'update': cmdUpdate,
} as const;
