// Auto-generated by commands/_internal/generate.ts -- do not edit
import cmdAgentsMd from '../agents-md/generate.ts';
import cmdConfigAgent from '../config/agent.ts';
import cmdConfigGet from '../config/get.ts';
import cmdConfigSet from '../config/set.ts';
import cmdDcpPreview from '../dcp/preview.ts';
import cmdDebugVisual from '../debug-visual/show.ts';
import cmdDoctor from '../doctor/run.ts';
import cmdDoctrineApprove from '../doctrine/approve.ts';
import cmdDoctrineDeprecate from '../doctrine/deprecate.ts';
import cmdDoctrineList from '../doctrine/list.ts';
import cmdDoctrineRead from '../doctrine/read.ts';
import cmdDoctrineSuggest from '../doctrine/suggest.ts';
import cmdDoctrineWrite from '../doctrine/write.ts';
import cmdExecutionInsights from '../execution-insights/show.ts';
import cmdFeatureActive from '../feature/active.ts';
import cmdFeatureComplete from '../feature/complete.ts';
import cmdFeatureCreate from '../feature/create.ts';
import cmdFeatureInfo from '../feature/info.ts';
import cmdFeatureList from '../feature/list.ts';
import cmdGraphInsights from '../graph/insights.ts';
import cmdGraphNext from '../graph/next.ts';
import cmdGraphPlan from '../graph/plan.ts';
import cmdHandoffAck from '../handoff/ack.ts';
import cmdHandoffReceive from '../handoff/receive.ts';
import cmdHandoffSend from '../handoff/send.ts';
import cmdHistory from '../history/run.ts';
import cmdInit from '../init/run.ts';
import cmdInstall from '../install/index.ts';
import cmdMemoryArchive from '../memory/archive.ts';
import cmdMemoryCompile from '../memory/compile.ts';
import cmdMemoryDelete from '../memory/delete.ts';
import cmdMemoryList from '../memory/list.ts';
import cmdMemoryPromote from '../memory/promote.ts';
import cmdMemoryRead from '../memory/read.ts';
import cmdMemoryStats from '../memory/stats.ts';
import cmdMemoryWrite from '../memory/write.ts';
import cmdPing from '../ping/run.ts';
import cmdPlanApprove from '../plan/approve.ts';
import cmdPlanComment from '../plan/comment.ts';
import cmdPlanCommentsClear from '../plan/comments-clear.ts';
import cmdPlanRead from '../plan/read.ts';
import cmdPlanRevoke from '../plan/revoke.ts';
import cmdPlanWrite from '../plan/write.ts';
import cmdSearchRelated from '../search/related.ts';
import cmdSearchSessions from '../search/sessions.ts';
import cmdSelfUpdate from '../update/self.ts';
import cmdSkill from '../skill/load.ts';
import cmdSkillList from '../skill/list.ts';
import cmdStatus from '../status/show.ts';
import cmdTaskBlock from '../task/block.ts';
import cmdTaskClaim from '../task/claim.ts';
import cmdTaskDone from '../task/done.ts';
import cmdTaskInfo from '../task/info.ts';
import cmdTaskList from '../task/list.ts';
import cmdTaskNext from '../task/next.ts';
import cmdTaskReportRead from '../task/report-read.ts';
import cmdTaskReportWrite from '../task/report-write.ts';
import cmdTaskSpecRead from '../task/spec-read.ts';
import cmdTaskSpecWrite from '../task/spec-write.ts';
import cmdTaskSync from '../task/sync.ts';
import cmdTaskUnblock from '../task/unblock.ts';
import cmdUpdate from '../update/run.ts';
import cmdVisual from '../visual/show.ts';

export const subCommands = {
  'agents-md': cmdAgentsMd,
  'config-agent': cmdConfigAgent,
  'config-get': cmdConfigGet,
  'config-set': cmdConfigSet,
  'dcp-preview': cmdDcpPreview,
  'debug-visual': cmdDebugVisual,
  'doctor': cmdDoctor,
  'doctrine-approve': cmdDoctrineApprove,
  'doctrine-deprecate': cmdDoctrineDeprecate,
  'doctrine-list': cmdDoctrineList,
  'doctrine-read': cmdDoctrineRead,
  'doctrine-suggest': cmdDoctrineSuggest,
  'doctrine-write': cmdDoctrineWrite,
  'execution-insights': cmdExecutionInsights,
  'feature-active': cmdFeatureActive,
  'feature-complete': cmdFeatureComplete,
  'feature-create': cmdFeatureCreate,
  'feature-info': cmdFeatureInfo,
  'feature-list': cmdFeatureList,
  'graph-insights': cmdGraphInsights,
  'graph-next': cmdGraphNext,
  'graph-plan': cmdGraphPlan,
  'handoff-ack': cmdHandoffAck,
  'handoff-receive': cmdHandoffReceive,
  'handoff-send': cmdHandoffSend,
  'history': cmdHistory,
  'init': cmdInit,
  'install': cmdInstall,
  'memory-archive': cmdMemoryArchive,
  'memory-compile': cmdMemoryCompile,
  'memory-delete': cmdMemoryDelete,
  'memory-list': cmdMemoryList,
  'memory-promote': cmdMemoryPromote,
  'memory-read': cmdMemoryRead,
  'memory-stats': cmdMemoryStats,
  'memory-write': cmdMemoryWrite,
  'ping': cmdPing,
  'plan-approve': cmdPlanApprove,
  'plan-comment': cmdPlanComment,
  'plan-comments-clear': cmdPlanCommentsClear,
  'plan-read': cmdPlanRead,
  'plan-revoke': cmdPlanRevoke,
  'plan-write': cmdPlanWrite,
  'search-related': cmdSearchRelated,
  'search-sessions': cmdSearchSessions,
  'self-update': cmdSelfUpdate,
  'skill': cmdSkill,
  'skill-list': cmdSkillList,
  'status': cmdStatus,
  'task-block': cmdTaskBlock,
  'task-claim': cmdTaskClaim,
  'task-done': cmdTaskDone,
  'task-info': cmdTaskInfo,
  'task-list': cmdTaskList,
  'task-next': cmdTaskNext,
  'task-report-read': cmdTaskReportRead,
  'task-report-write': cmdTaskReportWrite,
  'task-spec-read': cmdTaskSpecRead,
  'task-spec-write': cmdTaskSpecWrite,
  'task-sync': cmdTaskSync,
  'task-unblock': cmdTaskUnblock,
  'update': cmdUpdate,
  'visual': cmdVisual,
} as const;
