// Auto-generated by commands/_internal/generate.ts -- do not edit
import cmdAgentsMd from '../agents-md/generate.ts';
import cmdConfigAgent from '../config/agent.ts';
import cmdConfigGet from '../config/get.ts';
import cmdConfigSet from '../config/set.ts';
import cmdFeatureActive from '../feature/active.ts';
import cmdFeatureComplete from '../feature/complete.ts';
import cmdFeatureCreate from '../feature/create.ts';
import cmdFeatureInfo from '../feature/info.ts';
import cmdFeatureList from '../feature/list.ts';
import cmdInit from '../init/run.ts';
import cmdMemoryArchive from '../memory/archive.ts';
import cmdMemoryCompile from '../memory/compile.ts';
import cmdMemoryDelete from '../memory/delete.ts';
import cmdMemoryList from '../memory/list.ts';
import cmdMemoryRead from '../memory/read.ts';
import cmdMemoryStats from '../memory/stats.ts';
import cmdMemoryWrite from '../memory/write.ts';
import cmdPlanApprove from '../plan/approve.ts';
import cmdPlanComment from '../plan/comment.ts';
import cmdPlanCommentsClear from '../plan/comments-clear.ts';
import cmdPlanRead from '../plan/read.ts';
import cmdPlanRevoke from '../plan/revoke.ts';
import cmdPlanWrite from '../plan/write.ts';
import cmdSelfUpdate from '../update/self.ts';
import cmdSkill from '../skill/load.ts';
import cmdSkillList from '../skill/list.ts';
import cmdStatus from '../status/show.ts';
import cmdTaskInfo from '../task/info.ts';
import cmdTaskList from '../task/list.ts';
import cmdTaskReportRead from '../task/report-read.ts';
import cmdTaskReportWrite from '../task/report-write.ts';
import cmdTaskSpecRead from '../task/spec-read.ts';
import cmdTaskSpecWrite from '../task/spec-write.ts';
import cmdTaskSync from '../task/sync.ts';
import cmdUpdate from '../update/run.ts';

export const subCommands = {
  'agents-md': cmdAgentsMd,
  'config-agent': cmdConfigAgent,
  'config-get': cmdConfigGet,
  'config-set': cmdConfigSet,
  'feature-active': cmdFeatureActive,
  'feature-complete': cmdFeatureComplete,
  'feature-create': cmdFeatureCreate,
  'feature-info': cmdFeatureInfo,
  'feature-list': cmdFeatureList,
  'init': cmdInit,
  'memory-archive': cmdMemoryArchive,
  'memory-compile': cmdMemoryCompile,
  'memory-delete': cmdMemoryDelete,
  'memory-list': cmdMemoryList,
  'memory-read': cmdMemoryRead,
  'memory-stats': cmdMemoryStats,
  'memory-write': cmdMemoryWrite,
  'plan-approve': cmdPlanApprove,
  'plan-comment': cmdPlanComment,
  'plan-comments-clear': cmdPlanCommentsClear,
  'plan-read': cmdPlanRead,
  'plan-revoke': cmdPlanRevoke,
  'plan-write': cmdPlanWrite,
  'self-update': cmdSelfUpdate,
  'skill': cmdSkill,
  'skill-list': cmdSkillList,
  'status': cmdStatus,
  'task-info': cmdTaskInfo,
  'task-list': cmdTaskList,
  'task-report-read': cmdTaskReportRead,
  'task-report-write': cmdTaskReportWrite,
  'task-spec-read': cmdTaskSpecRead,
  'task-spec-write': cmdTaskSpecWrite,
  'task-sync': cmdTaskSync,
  'update': cmdUpdate,
} as const;
