#!/usr/bin/env bun
// Build-time generator: scans command files in src/commands/
// and emits src/commands/registry.generated.ts

import { readdir, writeFile } from 'fs/promises';
import { join } from 'path';

const COMMANDS_DIR = import.meta.dir;
const OUT_FILE = join(COMMANDS_DIR, 'registry.generated.ts');

const EXCLUDED = new Set(['generate.ts', 'registry.generated.ts']);

function toCamelCase(slug: string): string {
  return (
    'cmd' +
    slug
      .split('-')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
  );
}

async function main() {
  const entries = await readdir(COMMANDS_DIR);
  const commandFiles = entries
    .filter((f) => f.endsWith('.ts') && !f.startsWith('_') && !EXCLUDED.has(f))
    .sort();

  const imports = commandFiles
    .map((f) => {
      const slug = f.replace(/\.ts$/, '');
      const varName = toCamelCase(slug);
      return `import ${varName} from './${f}';`;
    })
    .join('\n');

  const mapEntries = commandFiles
    .map((f) => {
      const slug = f.replace(/\.ts$/, '');
      const varName = toCamelCase(slug);
      return `  '${slug}': ${varName},`;
    })
    .join('\n');

  const code = `// Auto-generated by commands/generate.ts -- do not edit
${imports}

export const subCommands = {
${mapEntries}
} as const;
`;

  await writeFile(OUT_FILE, code, 'utf-8');
  console.log(`[ok] Generated ${OUT_FILE} with ${commandFiles.length} commands`);
}

main().catch((err) => {
  console.error('[!] commands/generate.ts failed:', err);
  process.exit(1);
});
