#!/usr/bin/env bun
// Build-time generator: scans command files in src/commands/
// and emits src/commands/registry.generated.ts

import { readdir, writeFile } from 'fs/promises';
import { join } from 'path';

const COMMANDS_DIR = import.meta.dir;
const OUT_FILE = join(COMMANDS_DIR, 'registry.generated.ts');

const EXCLUDED = new Set(['generate.ts', 'registry.generated.ts']);

function toCamelCase(slug: string): string {
  return (
    'cmd' +
    slug
      .split('-')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
  );
}

async function main() {
  const entries = await readdir(COMMANDS_DIR, { withFileTypes: true });

  // Collect root-level command files
  const rootCommands = entries
    .filter(
      (e) =>
        e.isFile() &&
        e.name.endsWith('.ts') &&
        !e.name.startsWith('_') &&
        !EXCLUDED.has(e.name),
    )
    .map((e) => ({
      slug: e.name.replace(/\.ts$/, ''),
      importPath: `./${e.name}`,
    }));

  // Collect subdirectory command files in parallel
  const subdirResults = await Promise.all(
    entries
      .filter((e) => e.isDirectory())
      .map(async (dir) => {
        const subs = await readdir(join(COMMANDS_DIR, dir.name), {
          withFileTypes: true,
        });
        return subs
          .filter((e) => e.isFile() && e.name.endsWith('.ts') && !e.name.startsWith('_'))
          .map((e) => ({
            slug: `${dir.name}-${e.name.replace(/\.ts$/, '')}`,
            importPath: `./${dir.name}/${e.name}`,
          }));
      }),
  );

  const commands = [...rootCommands, ...subdirResults.flat()].sort((a, b) =>
    a.slug.localeCompare(b.slug),
  );

  // Detect slug collisions (e.g. root `foo-bar.ts` vs subdir `foo/bar.ts`)
  const seen = new Set<string>();
  for (const { slug } of commands) {
    if (seen.has(slug)) console.warn(`[!] slug collision: ${slug}`);
    seen.add(slug);
  }

  // Pre-compute varName once per command
  const enriched = commands.map((cmd) => ({ ...cmd, varName: toCamelCase(cmd.slug) }));

  const imports = enriched
    .map(({ varName, importPath }) => `import ${varName} from '${importPath}';`)
    .join('\n');

  const mapEntries = enriched
    .map(({ slug, varName }) => `  '${slug}': ${varName},`)
    .join('\n');

  const code = `// Auto-generated by commands/generate.ts -- do not edit
${imports}

export const subCommands = {
${mapEntries}
} as const;
`;

  await writeFile(OUT_FILE, code, 'utf-8');
  console.log(`[ok] Generated ${OUT_FILE} with ${commands.length} commands`);
}

main().catch((err) => {
  console.error('[!] commands/generate.ts failed:', err);
  process.exit(1);
});
