#!/usr/bin/env bun
// Build-time generator: scans command files in src/commands/
// and emits src/commands/registry.generated.ts

import { readdir, writeFile } from 'fs/promises';
import { join } from 'path';

const COMMANDS_DIR = import.meta.dir;
const OUT_FILE = join(COMMANDS_DIR, 'registry.generated.ts');

const EXCLUDED = new Set(['generate.ts', 'registry.generated.ts']);

function toCamelCase(slug: string): string {
  return (
    'cmd' +
    slug
      .split('-')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
  );
}

async function main() {
  const entries = await readdir(COMMANDS_DIR, { withFileTypes: true });
  const commands: Array<{ slug: string; importPath: string }> = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const subEntries = await readdir(join(COMMANDS_DIR, entry.name));
      for (const sub of subEntries.filter(
        (f) => f.endsWith('.ts') && !f.startsWith('_'),
      )) {
        const basename = sub.replace(/\.ts$/, '');
        commands.push({
          slug: `${entry.name}-${basename}`,
          importPath: `./${entry.name}/${sub}`,
        });
      }
    } else if (
      entry.name.endsWith('.ts') &&
      !entry.name.startsWith('_') &&
      !EXCLUDED.has(entry.name)
    ) {
      commands.push({
        slug: entry.name.replace(/\.ts$/, ''),
        importPath: `./${entry.name}`,
      });
    }
  }
  commands.sort((a, b) => a.slug.localeCompare(b.slug));

  const imports = commands
    .map((cmd) => {
      const varName = toCamelCase(cmd.slug);
      return `import ${varName} from '${cmd.importPath}';`;
    })
    .join('\n');

  const mapEntries = commands
    .map((cmd) => {
      const varName = toCamelCase(cmd.slug);
      return `  '${cmd.slug}': ${varName},`;
    })
    .join('\n');

  const code = `// Auto-generated by commands/generate.ts -- do not edit
${imports}

export const subCommands = {
${mapEntries}
} as const;
`;

  await writeFile(OUT_FILE, code, 'utf-8');
  console.log(`[ok] Generated ${OUT_FILE} with ${commands.length} commands`);
}

main().catch((err) => {
  console.error('[!] commands/generate.ts failed:', err);
  process.exit(1);
});
