#!/usr/bin/env bun
// Build-time generator: reads skills/[name]/SKILL.md frontmatter
// and emits src/skills/registry.generated.ts

import { readdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { parseFrontmatter } from '../utils/frontmatter.ts';

const ROOT = join(import.meta.dir, '..', '..');
const SKILLS_DIR = join(ROOT, 'skills');
const OUT_FILE = join(ROOT, 'src', 'skills', 'registry.generated.ts');

interface SkillMeta {
  slug: string;
  name: string;
  description: string;
  path: string;
}

async function main() {
  const entries = await readdir(SKILLS_DIR, { withFileTypes: true });
  const dirs = entries.filter((e) => e.isDirectory()).map((e) => e.name).sort();

  const skills: SkillMeta[] = [];

  for (const slug of dirs) {
    const mdPath = join(SKILLS_DIR, slug, 'SKILL.md');
    let raw: string;
    try {
      raw = await readFile(mdPath, 'utf-8');
    } catch {
      console.warn(`[!] Skipping ${slug}: no SKILL.md`);
      continue;
    }

    const fm = parseFrontmatter(raw);
    if (!fm?.name || !fm?.description) {
      console.warn(`[!] Skipping ${slug}: missing name or description in frontmatter`);
      continue;
    }

    skills.push({
      slug,
      name: fm.name,
      description: fm.description,
      path: `skills/${slug}/SKILL.md`,
    });
  }

  const names = skills.map((s) => `'${s.slug}'`).join(', ');

  const entries_ = skills
    .map(
      (s) =>
        `  '${s.slug}': { name: '${s.slug}', description: ${JSON.stringify(s.description)}, path: '${s.path}' },`,
    )
    .join('\n');

  const code = `// Auto-generated by src/skills/generate.ts -- do not edit
export const BUILTIN_SKILL_NAMES = [${names}] as const;
export type BuiltinSkillName = typeof BUILTIN_SKILL_NAMES[number];
export const BUILTIN_SKILLS: Record<BuiltinSkillName, { name: string; description: string; path: string }> = {
${entries_}
};
`;

  await writeFile(OUT_FILE, code, 'utf-8');
  console.log(`[ok] Generated ${OUT_FILE} with ${skills.length} skills`);
}

main().catch((err) => {
  console.error('[!] generate.ts failed:', err);
  process.exit(1);
});
